# Generated by Django 4.0.2 on 2022-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foodtypes',
            new_name='FoodType',
        ),
        migrations.AddField(
            model_name='type',
            name='totalCal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
