# Generated by Django 4.0.2 on 2022-05-25 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 5, 39, 50, 24652, tzinfo=utc), verbose_name='date published'),
        ),
    ]
