# Generated by Django 4.0.2 on 2022-05-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rename_foodtypes_foodtype_type_totalcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='totalCal',
            field=models.IntegerField(blank=True),
        ),
    ]
