# Generated by Django 4.0.2 on 2022-05-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_type_foodrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='foodRate',
            field=models.CharField(default='One Star', max_length=20),
        ),
    ]
