# Generated by Django 4.0.2 on 2022-05-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_addcal_rename_name_type_foodtype_type_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
