# Generated by Django 4.0.2 on 2022-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_type_foodrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ratePost',
            field=models.CharField(choices=[('1 star', 'One star'), ('2 stars', 'Two stars'), ('3 stars', 'Three stars'), ('4 stars', 'Four stars'), ('5 stars', 'Five stars'), ('6 stars', 'Six stars'), ('7 stars', 'Seven stars'), ('8 stars', 'Eight stars'), ('9 stars', 'Nine stars'), ('10 stars', 'Ten stars')], default='1 star', max_length=50),
        ),
    ]
