# Generated by Django 4.0.2 on 2022-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_delete_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='log',
            field=models.CharField(choices=[('p', 'protein'), ('c', 'carbohydrates'), ('l', 'lipids')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
