# Generated by Django 4.0.2 on 2022-05-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_type_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('p', 'protein'), ('c', 'carbohydrates'), ('l', 'lipids')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='type',
            name='log',
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.foodtype'),
        ),
        migrations.DeleteModel(
            name='AddCal',
        ),
    ]
