# Generated by Django 4.0.2 on 2022-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_foodtype_remove_type_log_alter_type_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
