# Generated by Django 4.0.2 on 2022-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_foodtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('p', 'protein'), ('c', 'carbohydrates'), ('l', 'lipids')], default='protein', max_length=13),
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
