# Generated by Django 4.0.2 on 2022-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upload',
            field=models.ImageField(default=0, upload_to='calulator/images/profile'),
            preserve_default=False,
        ),
    ]
