# Generated by Django 4.0.2 on 2022-05-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_remove_userprofile_image_userprofile_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='upload',
        ),
    ]
