# Generated by Django 4.0.2 on 2022-05-23 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0010_totaltoday_rename_type_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TotalToday',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='totalCal',
            new_name='foodRate',
        ),
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.AddField(
            model_name='type',
            name='foodName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='foodType',
            field=models.CharField(choices=[('d', 'dessert'), ('m', 'main course'), ('a', 'appetizer')], default='dessert', max_length=50),
        ),
    ]
