# Generated by Django 4.0.2 on 2022-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_alter_profilepicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(default='blank-profile-picture-973460__4800.webp.jpg', upload_to='profile_pics'),
        ),
    ]
