# Generated by Django 4.0.2 on 2022-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_type_foodpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='foodType',
            field=models.CharField(default='dessert', max_length=50),
        ),
    ]
