# Generated by Django 4.0.2 on 2022-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_alter_userprofile_image_delete_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/blank-profile-picture-973460__4800.webp.jpg', upload_to='profile_pics'),
        ),
    ]
