# Generated by Django 4.0.2 on 2022-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(default=''),
        ),
    ]
