# Generated by Django 4.0.2 on 2022-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_alter_comment_comment_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='foodComment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/profile.jpeg', upload_to='profile_pics'),
        ),
    ]
