# Generated by Django 4.0.2 on 2022-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='foodRate',
            field=models.IntegerField(),
        ),
    ]
