# Generated by Django 4.0.2 on 2022-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_alter_type_foodcomment_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='foodImage',
            field=models.ImageField(default='food_pics/blank.jpeg', upload_to='profile_pics'),
        ),
    ]
