# Generated by Django 4.0.2 on 2022-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0018_type_foodimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='foodType',
            field=models.CharField(choices=[('Dessert', 'dessert'), ('Main Course', 'main course'), ('Appetizer', 'appetizer')], default='Dessert', max_length=50),
        ),
    ]
